[package]
name = "grab-invoices"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
google-gmail1 = "5.0.0"
yup-oauth2 = "8.3.0"
chrono = "0.4"
base64 = "0.21"
