[package]
name = "grab-invoices"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
google-gmail1 = "5.0.5"
base64 = "0.21"
chrono = "0.4"
serde_json = "1.0.148"
